# Generated by Django 5.1.2 on 2024-12-27 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='academictable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Hqul', models.CharField(max_length=100)),
                ('Passout', models.IntegerField()),
                ('Degree', models.CharField(max_length=100)),
                ('Spec', models.CharField(max_length=500)),
                ('inst', models.CharField(max_length=100)),
                ('addt', models.CharField(max_length=500)),
                ('Type', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tenth_certificate', models.FileField(upload_to='documents/tenth_certificates/')),
                ('twelfth_certificate', models.FileField(upload_to='documents/twelfth_certificates/')),
                ('degree_certificate', models.FileField(upload_to='documents/degree_certificates/')),
                ('masters_certificate', models.FileField(blank=True, null=True, upload_to='documents/masters_certificates/')),
                ('aadhar_card', models.FileField(upload_to='documents/aadhar_cards/')),
                ('passport', models.FileField(blank=True, null=True, upload_to='documents/passports/')),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='documents/pan_cards/')),
            ],
        ),
        migrations.CreateModel(
            name='financialtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Bank_name', models.CharField(max_length=100)),
                ('Account_number', models.IntegerField()),
                ('Account_type', models.CharField(max_length=100)),
                ('Investments', models.CharField(max_length=500)),
                ('Assets', models.CharField(max_length=100)),
                ('Credit_score', models.IntegerField()),
                ('Type', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='medicaltable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('blood_group', models.CharField(max_length=3)),
                ('Gender', models.CharField(max_length=50)),
                ('ill', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='personaltable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('Email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('Type', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='registertable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='logintable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('Loginid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appv.registertable')),
            ],
        ),
    ]
